# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  config:
    desc: ensure config for github cli is set to create releases at jenkinsci
    cmds:
      - |
        if ! gh config get prompt; then
          echo "configuring github cli"
          gh repo set-default jenkinsci/thycotic-devops-secrets-vault-plugin
        fi
  bump:
    desc: bump the version using changie
    cmds:
      - changie batch auto
      - changie merge
      - git add .changes/*
      - git add CHANGELOG.md
  changelog:refresh:
    desc: refresh the changelog without trying to create a new version
    cmds:
      - changie merge
  changelog:latest:
    desc: show the latest changelog entry (which will power the release draft)
    cmds:
      - glow .changes/$(changie latest).md
  release:
    desc: create a draft release called "next" for jenkinsci to create a release from once PR merged
    interactive: true
    cmds:
      - |
        gum format "## Draft Release Content"
        glow ".changes/$(changie latest).md"
        gum confirm "proceed with creating draft release?" && gh release create --title 'next' --tag 'next' --draft --notes-file=.changes/$(changie latest).md
