# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  bump:
    desc: bump the version using changie
    cmds:
      - changie batch auto
      - changie merge
  changelog:refresh:
    desc: refresh the changelog without trying to create a new version
    cmds:
      - changie merge
  release:
    desc: create a draft release called "next" for jenkinsci to create a release from once PR merged
    interactive: true
    cmds:
      - |
        echo "creating draft release called 'next' based on changelog file: changes/$(change latest).md"
        gum confirm "proceed with creating draft release?" && gh release create next --draft --notes-file=changes/$(change latest).md
